<robot name="camera" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_wide" value="0.025" />
    <xacro:property name="camera_high" value="0.025" />

    <xacro:macro name="camera_fun" params="link_name_3">
        <link name="${link_name_3}">
            <visual>
                <geometry>
                    <box size="${camera_length} ${camera_wide} ${camera_high}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 1.57" />
                <material name="black" />
            </visual>
        </link>
        <joint name="dipan_camera" type="continuous">
            <parent link="dipan" />
            <child link="${link_name_3}" />
            <origin xyz="0 ${dipan_radius/2} ${(dipan_length/2+camera_wide/2)}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
        </joint>
    </xacro:macro>
    <xacro:camera_fun link_name_3="camera" />
</robot>